-- 1. Nombre Paciente, NumConsultas
-- 2. Nombre Medicamento, Num Veces Recetado de mayor a menor
-- 3. Detalle de consultas de un paciente, como stored procedure
-- Datos: fecha consulta, edad paciente, doctor, peea, nota clínica
-- 4. Fecha inicio/fin Detalle paciente, nombre paciente, address, birthdate, todo lo del punto 4